# 欢迎使用 ⚡️serverless⚡️ 组件
#
# serverless组件是基于具体使用场景(Express, 静态网站等)提供的定制云资源编排和组织的解决方案。
# 这是serverless的主要配置文件，包含了一些使用示例以及注释说明。
# 您只需几行配置描述，即可进行云函数、API 网关、COS、DB 等
# Serverless 资源进行快速创建、部署和修改。
#
# 有关完整的配置选项，请检查文档：
# https://cloud.tencent.com/document/product/1154/51080
#
# 使用愉快

# ##应用信息##
component: vpc # [必选]使用组件的名称，更多在 https://github.com/serverless-components
name: fullstack-vpc # [必选]组件的实例名称。
app: fullstack-serverless-vpc # app应用名称(同账号下应用名称唯一)。留空则取当前组件的实例名称。如果项目根目录中的配置文件存在此字段，会继承根目录配置文件中相应字段的值
# stage: dev # app 环境字段，留空默认值为dev。如果项目根目录中的配置文件存在此字段，会继承根目录配置文件中相应字段的值


# ##Vpc 组件配置##
# 更多内容请查看：https://github.com/serverless-components/tencent-vpc/blob/master/docs/configure.md
inputs:
  region: ${env:REGION} # VPC 的所属地区
  zone: ${env:ZONE} VPC 所在地区的区域
  vpcName: serverless # VPC 的名称
  subnetName: serverless # Subnet 的名称
