org: serverless
app: fullstack-nosql
stage: dev
component: scf
name: fullstack-backend

inputs:
  name: ${name}
  src: ./src
  runtime: Nodejs10.15
  region: ap-guangzhou
  handler: index.main
  environment:
    variables:
      # 请填入您的SecretId
      SecretId: ${env:TENCENT_SECRET_ID}
      # 请填入您的SecretKey
      SecretKey: ${env:TENCENT_SECRET_KEY}
      MongoId: ${output:${stage}:${app}:fullstack-db.EnvId}
  events:
    - apigw:
        name: MongoDBDemo
        parameters:
          protocols:
            - http
            - https
          serviceName:
          description: The service of Serverless Framework - MongoDB
          environment: release
          endpoints:
            - path: /users
              enableCORS: TRUE
              method: POST
