component: website
name: fullstack-frontend
org: serverless
app: fullstack-nosql
stage: dev

inputs:
  src:
    src: ./src
    hook: npm run build
    index: index.html
    error: index.html
    envPath: ./
  region: ap-guangzhou
  bucketName: my-bucket
  protocol: http
  env:
    apiUrl: ${output:${stage}:${app}:fullstack-backend.triggers.apigw.0}
