component: postgresql
name: sls-db

inputs:
  region: ap-guangzhou
  zone: ap-guangzhou-2
  dBInstanceName: ${name}-${stage}
  extranetAccess: true
  vpcConfig:
    vpcId: ${output:${stage}:${app}:sls-vpc.vpcId}
    subnetId: ${output:${stage}:${app}:sls-vpc.subnetId}
