# 欢迎使用 ⚡️serverless⚡️ 组件
#
# serverless组件是基于具体使用场景(Express, 静态网站等)提供的定制云资源编排和组织的解决方案。
# 这是serverless的主要配置文件，包含了一些使用示例以及注释说明。
# 您只需几行配置描述，即可进行云函数、API 网关、COS、DB 等
# Serverless 资源进行快速创建、部署和修改。
#
# 有关完整的配置选项，请检查文档：
# https://cloud.tencent.com/document/product/1154/51080
#
# 👩‍💻 Happy Coding 👨‍💻

# ##应用信息##
app: appDemo # app名称(app唯一识别标识)。同账号下需唯一，留空则继承组件实例名称
component: nuxtjs # [必选]要使用组件，更多组件请查看 https://github.com/serverless-components
name: nuxtjsDemo # [必选]组件实例名称

# ##nuxtjs 组件配置##
# 更多内容请查看：https://github.com/serverless-components/tencent-nuxtjs/blob/master/docs/configure.md
inputs:
  src: # 执行目录
    hook: npm run build # 构建命令。在代码上传之前执行
    dist: ./ # 输出的目录。如果配置 hook，此参数必填
    exclude:
      - .env
  region: ap-guangzhou # 部署目标地区。 更多参考 https://cloud.tencent.com/document/api/583/17238#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8
  runtime: Nodejs10.15 # 运行环境。[Nodejs10.15, Nodejs12.16]
  apigatewayConf: # API 网关
    protocols:
      - http
      - https
    environment: release # 发布环境。[test, prepub，release]
    # isBase64Encoded: true # 项目中如果涉及到文件上传，需要依赖 API 网关提供的 Base64 编码支持
    #customDomains: # 自定义域名绑定
    #  - domain: abc.com # 待绑定的域名
    #    certificateId: abcdefg # 待绑定域名的证书 ID
    #    isDefaultMapping: false # 如要设置自定义路径映射，请设置为 false
    #    # 自定义路径映射。可一次仅映射一个 path 到一个环境，也可映射多个 path 到多个环境。
    #    # 一旦使用自定义映射，默认映射规则不再生效。
    #    pathMappingSet:
    #      - path: /
    #        environment: release
    #    protocols:
    #      - http
    #      - https
