name: Publish and test scf-php

on:
  push:
    branches: [ master ]
    paths: [ 'scf-php/**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publishAndTest:
    runs-on: ubuntu-latest
    env:
      TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
      TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
      SERVERLESS_PLATFORM_VENDOR: tencent
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install serverless cli
        run: sudo npm i serverless -g
      - name: Publish template
        run: cd scf-php && sls publish
      - name: Test template
        run: |
          sls init scf-php --name test-scf-php
